### ISSUE TITLE
Autoprefixer

### ISSUE THREAD

**Issue by dblodorn** [morishitter/picostyle#38]
@morishitter - Curious if there is there support for auto-prefixer / browserlist?

**Comment by morishitter** [comment]
@dblodorn Picostyle gets a pure JavaScript object e.g. `{ fontSize: 18, color: '#555' }`, so we can use with [postcss-js](https://github.com/postcss/postcss-js) syntax plugin. Some users may not need autoprefixer because for example, they support only Chrome or some modern browsers. Users can control other front-end toolchains.

**Comment by dblodorn** [comment]
@morishitter good to know - thanks for pointing out postcss-js module. And thanks for publishing picostyle! just getting into a hyperapp - app, and its great to not have to drop the styled-components workflow!
